{% set version = "4.0.4" %}
{% set name = "givaro" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/linbox-team/givaro/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 65257ee07183b8cbd50add2e36b1bc757f1459e665ae02cd662777d4001ba1dd

build:
  number: 1001
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('givaro', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
  host:
    - gmp
  run:
    - gmp

test:
  commands:
    - test -f ${PREFIX}/include/givaro/givaromm.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: http://givaro.forge.imag.fr
  license: GPLv2+
  license_file: {{ SRC_DIR }}/COPYING
  summary: Givaro - C++ library for arithmetic and algebraic computations
  dev_url: https://github.com/linbox-team/givaro
  doc_url: http://givaro.forge.imag.fr/givaro-html

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
