appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: C+j2RiexveeEcvoF9c/XsDy0Zt3wloQlzWKoJSX0hY97ajli3V6X4HiUrOsea4Z8lXedsbOn33S11uqsM6byEkuyJD93XwRB+YIvov8M65QgvjJ9Omcw9pPTdhJyPkCFxlNq7/Ejv5glAHOKrxoMMHeXexmbzq++zlgfd3bIhE8Aa0YxHReWUDKO0cTrEKMpmt5ofNXL55qKDaXxHEuXbJC812q6smiXTTHr37o5FRtxhFj5d68/UVq+xIufDpWtplupXGegYhokmN5RhbiZ3FTIt28xMX920YiibFhxVTQNrhQRaKfxNE/yhPJR2TTOBsIiWHmpTIV1uy4TZP5X2G7N1FyUe7/Pa9xS4Swaxii96JBFTuOeqr1j26Q+UPK3vetDfKx+zm1hGjWDrtRoh7NJGL2oHGeiVULS5ubNHbferPlXJ9xo/G9I4Eol8t50CoZNBf2K8qK05LwFKzh8rtKvBY2aNcwkLyQ4rsKPszW92PQAEfPFTg5QOf0blut7FVl29lWyt2CkZl5aAE9saAHMlO/SvnzXDYppMvXulCOjgw66P50XK+u4gdy5Hai6+HgQm4W704ChqbeohMNVttsZNV8lzY9BLGffrb5/qDoxQ6Iuq+3abHwnWIp5nPFKzd464ttuHzfC0UHHu2O6Hug266tjjMBK9JkTtztTf1M=}
