travis:
  secure:
    BINSTAR_TOKEN: U0wyY/junxa0BfrvcRukELUv0gxRJjTMtGLqDY6hHWCE1K82oTvq5I43JHl+XxQ31gzzyqxjDQBPxN6Ha1pg/nO7Upfy8vGcwRCIbwCoGJfzmpHW2sSzHHA6y4bUupFoumkGHRbBz6e345O2GP1WLVyyMfqg8N/Xky4rxVqUtHQX5p8oIetGL+W6KQq+V6XObEBK9QrpfOtAEJuM7dscQBEtL7vQWnBTLBss65N4ZQup0h1+oNlPDmGqK73bWxa2Zxf/9KYeZU5FF5i7M0numN2jSvrRNFysL4oKcuswpVwXDbH7R3DR5epRplZ0mVjpL63Naz2U14MNYx6VD3Sc7DgXrLA2NwFrBILd0eumerBuvh36nJiaC96YTKJecoeMt9Gvwf4n3oV821ki5+Wh5Zhzq6m3BmLF+hj66J08PfOWsW/vN1WrPTWGZPyIzJRr28F0AOaeuxKsDJfHffYKobtutH524k284d0H0Pgf4woYsAWaqa/YWvZ26Y2/LV/t3IB3ao4BzkxPslODdeMGGA8H6p2FYiDWTgLbDQIF9w856jsdGoDG4vqr5KNOf0Nm7G2XiLkQBDh95hQdS9V5qhzgB99JN2AXNb8GLVIbEFcfAecOJ7I+l+f2ynxkqTnvf7V+aePeJ8Hk5n9bgNFETA9OvgkbyytusdIb3CslQ8s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
