travis:
  secure:
    BINSTAR_TOKEN: IAfu2lwzZNgl94wg0QfTpfvoMer12cTm3QTjgO74CuJAKIiSbKUjOCnI4s4GbKyVr0zGcxalGKqbZhpCKIdyhivGcL+0pVRQFApuOQrFxFEaIs1DiJMlTWTZk40W5MJaliyTzw+A+s4xrcqdEp9S30ItcRP44HK9laj5nbf/FzOD6b5nNes7qzhZ4WBUzR338XGHdSF3AjjVhLyhqbDxPgiPBAZQ8k97KlSmttopfmckBtpDkAFN6NqXKLxRkx248kfB8tCvWEzArAQMSkd8QoFqTnxdkfArkptTFCzzk+oDaMxAiPVU/gaws2kr0LA3ANjGhHhdg0NUb1xPB/+Usd+IP2HB6+TLZg4t6eQwnKduuqOsfBwM2YOgbqv0sjnVvCeu8UGCmP7VZde0ukjvnuQoOh4mDGIEhaZY6diLfNcmqyQ62pWT/nvFoXnvT3rpheWXA0FOy0CY/enajiAD9PH5F+y7hIf7EClzMNarnEYTqWzHsvTpqO23hw6Fvw9VJ+RIctonUP/4BeKZKL9oLikLPxlsS3gj2B8r8Rs4wBA8j8H07sXdgta+2882DibKlF5gKWTrzQPfibjUPKDXy+5WlgyQ77X+bb/IU0vYcSjcE5MSkr7qPIvE5lbXFYf07PvZ4PzFu7+VeIKXgjgMWUccqGTE0L4cSgPRUYDJyDE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
